[package]
name = "rasusa"
description = "Randomly subsample reads to a specified coverage"
version = "0.7.1"
authors = ["Michael Hall <michael@mbh.sh>"]
edition = "2018"
repository = "https://github.com/mbhall88/rasusa"
homepage = "https://github.com/mbhall88/rasusa"
readme = "README.md"
keywords = ["bioinformatics", "subsampling", "fastq", "fasta", "coverage"]
categories = ["science", "command-line-utilities"]
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[badges]
maintenance = { status = "actively-developed" }

[dependencies]
clap = { version = "3.2.8", features = ["derive"]}
regex = "1.5.5"
thiserror = "1.0"
anyhow = "1.0"
needletail = { version = "0.5.1", features = ["compression"] }
rand = "0.7.2"
rand_pcg = "0.2.1"
log = "0.4"
chrono = "0.4"
niffler = "2.3"
env_logger = "0.10.1"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3.1.0"
